#archivo make con las reglas  incluidas para compilar y ejecutar el programa
compile:
	gcc Sistema_vuelos.c -g -o Sistema_vuelos
run: compile
	./Sistema_vuelos
debug:
	gdb Sistema_vuelos
clean:
	rm Sistema_vuelos
